name: Working Directory and Shells
on: [push]

jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display Working Directory and List Files
              run: |
                pwd
                ls -ltrh
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
